/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Suvalien (https://sketchfab.com/Suvalien)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sugar-teddy-bear-8fbc11e8876d4ac7b22190c07e96726b
title: Sugar Teddy Bear
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/TeddyBear.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group>
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} skeleton={nodes.Object_9.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/TeddyBear.gltf')
